### PR TITLE
Fix decoding triplet into MSB and LSB (byte)

### PR DESCRIPTION
**Pull request by cdeletre**
Hi Thomas,

First thank you for initiating the support of base45 into CyberChef. I think, the way you are transforming the triplet into the MSB and LSB byte is incorrect. If MSB or LSB is 0x00 it shouldn't be ignored. Here is in this PR a proposal to fix this. Let me know if you disagree ;)

Have a nice day !

Cyril

### CODE REVIEW

**Comment by t-8ch** [comment]
Thanks for the PR!
I cherry-picked b61ec14 .
(And confused GitHub horribly)

For b7f93cc I think we do have to skip the result of `b >> 8` if it is zero. Otherwise we will fail Example 4.4 from the RFC.
Would you mind if I integrated your changes into my commits, so the history stays clear?
I would add you as "Co-developed-by".

**Comment by cdeletre** [comment]
Hi Thomas,

Thank for your proposing to mention me as a co-developer. I'm fine with this, even I didn't except it ;)

Regarding the skipping of `b>>8` when it's `0`, after looking at the example it's more tricky. I haven't thought about it when I was writing the "hot fix" but now I remember that, like in other base encoding, it only happens when the last triplet you process is made of 2 bytes (instead of 3).

I can have a look at this to patch the code to handle this. I just need to see how I can trigger this with your Utils.chunked function ;)

Anyway, thanks again for starting the work on the Base45 operation, I have to say that I was a little bit lazy a doing this in the moment ;)

**Comment by cdeletre** [comment]
Here is the fix. I haven't tested it  in depth, but it works with `QED8WEX0` and convert it to `ietf!`. It also works with my EU Digital Covid Certificate.

**Comment by t-8ch** [comment]
@cdeletre I added your changes. Thanks a lot!

**Comment by cdeletre** [comment]
> @cdeletre I added your changes. Thanks a lot!

You're welcome ;)

**Pull request closed without merging**
